#!/bin/bash

echo "///////////// BEGINNING TAK SERVER CREATION ///////////////"

# CHECK IF THE NECESSARY FILES ARE IN THE FOLDER
echo "1) Checking if files exist... "


if [[ ! -f ./deb_policy.pol ]]; then 
	echo "	Could not find deb_policy.pol"
	exit 1
fi

if [[ ! -f ./takserver_5.2-RELEASE30_all.deb ]]; then
	echo "	Count not find takserver deb file"
	exit 1
fi

if [[ ! -f ./takserver-public-gpg.key ]]; then
	echo "	Could not find the public gpg key file"
	exit 1
fi

echo "Complete"
echo ""


# INSTALL DEBSIG VERIFY TOOL
echo "2) Installing debsig-verify..."

sudo apt install debsig-verify
echo "Complete"
echo ""

echo -n "In a seperate window: cat the debsig file and paste the id here: "
read id
echo ""

# CREATE DEBSIG FOLDERS, FILES, and VERIFY
echo "3) Creating debsig keyrings..."
sudo mkdir -p /usr/share/debsig/keyrings/${id}/
sudo mkdir -p /etc/debsig/policies/${id}/
sudo touch /usr/share/debsig/keyrings/${id}/debsig.gpg
sudo gpg --no-default-keyring --keyring /usr/share/debsig/keyrings/${id}/debsig.gpg --import ./takserver-public-gpg.key

sudo cp deb_policy.pol /etc/debsig/policies/${id}/debsig.pol

debsig-verify -v takserver_5.2-RELEASE30_all.deb
echo "Complete"
echo ""


# CREATE postgresql KEYRINGS
echo "4) Creating postgresql keyrings..."
sudo mkdir -p /etc/apt/keyrings
sudo curl https://www.postgresql.org/media/keys/ACCC4CF8.asc --output /etc/apt/keyrings/postgresql.asc
sudo sh -c 'echo "deb [signed-by=/etc/apt/keyrings/postgresql.asc] http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/postgresql.list'

echo "Complete"
echo ""


echo "5) Updating apt..."
sudo apt update
echo "Complete"
echo ""


echo "6) Installing takserver (this will take several minutes)..."
sudo apt install ./takserver_5.2-RELEASE30_all.deb
echo "Complete"
echo ""

echo "7) Updating java..."
sudo apt install openjdk-17-jre
echo "Complete"
echo ""

echo "8) Realoding daemon..."
sudo systemctl daemon-reload
echo "Complete"
echo ""

echo "//////////////// TAK SERVER INSTALLATION COMPLETE /////////////////"
